[package]
name = "c2"
version = "0.2.0"
authors = ["Ross <yeahross@protonmail.com>"]
edition = "2018"
description = "2D Collision Detection"
license = "MIT"
repository = "https://github.com/yeahross0/cute-c2"
readme = "../README.md"

[dependencies.c2-sys]
path = "../cute-c2-sys"
version = "0.2.0"
